---
title: "Symbiont density analysis"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")

# load packages
library(tidyverse)
```

# Import data
```{r}
# Cell count data
sym_counts <- read_csv("data/physiology/cell_density/cells.csv")

# Surface area data
sa <- read.csv("output/physiology/surface_area/surface_area.csv") 

# Tissue homogenate volume data
homog_vols <- read_csv("data/physiology/homog_vols.csv") %>% select(sample_id, total_slurry_ml, sym_vol_ml, host_vol_ml, resuspended_sym_vol_ml)

# Coral sample metadata
metadata <- read_csv("data/p_r_rates/pr_sample_metadata.csv") %>% select(sample_id, Species, Lifestage) %>% filter(!str_detect(sample_id, "^BK"))

# Join homogenate volumes and surface area with sample metadata
metadata <- full_join(metadata, homog_vols) %>%
  full_join(sa) %>% filter(!is.na(Species))
```




# Calculate cells per square centimeter
```{r}
# Calculate mean counts for each sample
sym_counts <- sym_counts %>%
  select(sample_id, squares_counted, matches("count[0-6]")) %>%
  gather("rep", "count", -sample_id, -squares_counted) %>%
  group_by(sample_id, squares_counted) %>%
  summarise(mean_count = mean(count, na.rm = TRUE))

# Join mean counts with sample metadata
sym_counts <- full_join(sym_counts, metadata)


# homogenate volume = total tissue
# sym aliquot volume = total tissue from which cells were taken
# sym resuspended volume = dilution of cells from total pellet 

#cells per mL = count * 10000 / squares counted 







# Normalize counts by homogenat volume and surface area
sym_counts <- sym_counts %>%
  mutate(cells.mL = mean_count * 10000 / squares_counted,
         cells = cells.mL * homog_vol_ml,
         cells.cm2 = cells / surface.area.cm2)
```








# Plot data
```{r}
sym_counts %>%
  filter(!is.na(site)) %>%
  ggplot(aes(x = site, y = cells.cm2 / 10^6, color = species)) +
  labs(x = "",y = "Cell Density (Cells/cm2 * 10^6)") +
  facet_wrap(~ species) +
geom_jitter(width = 0.1) +                                            # Plot all points
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
               geom = "errorbar", color = "black", width = 0.5) +
  stat_summary(fun.y = mean, geom = "point", color = "black")           # Plot mean
```


Output data to file.  

```{r}
sym_counts %>%
  select(colony_id, site, species, cells.cm2) %>%
  mutate(timepoint="timepoint1")%>%
  write_csv(path = "output/1_symb_densities.csv")


```
